{
 "title": "RKE2 metrics w/ longhorn",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "range", "label": "Range", "query": "1m,5m,10m,15m,20m,30m,1h" },
   { "name": "Namespaces", "label": "Namespaces", "query": { "query": "label_values(namespace)" } },
   { "name": "Node", "label": "Node", "query": { "query": "label_values(node)" } },
   { "name": "mount", "label": "mountpoint", "query": { "query": "label_values(mountpoint)" } },
   { "name": "device", "label": "device", "query": { "query": "label_values(device)" } }
  ]
 },
 "panels": [
  {
   "title": "Node Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes Ready",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"}==1)"
      }
     ]
    },
    {
     "title": "Nodes Ready",
     "type": "stat",
     "description": "With this panel be aware of the current time interval being used (top right option with the clock) as it will display what nodes have been out during that time entire interval, not just currently out. This can be used to see around when a node had gone out. ",
     "gridPos": { "h": 9, "w": 15, "x": 9, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(node) (kube_node_status_condition{condition=\"Ready\", status=\"true\"}==1)",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Nodes Not Ready",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"false\"}==1)"
      }
     ]
    },
    {
     "title": "Nodes Not Ready",
     "type": "stat",
     "description": "With this panel be aware of the current time interval being used (top right option with the clock) as it will display what nodes have been out during that time entire interval, not just currently out. This can be used to see around when a node had gone out. ",
     "gridPos": { "h": 9, "w": 15, "x": 9, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(node) (kube_node_status_condition{condition=\"Ready\", status=\"false\"}==1)",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Total Pods (Node)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (node) (kube_pod_info{node!=\"\", pod!~\"helm-install.*\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Pods (Namespace) {$Node}",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_pod_info{pod!~\"helm-install.*\",node=~\"$Node\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods With No Running Containers ",
     "type": "stat",
     "description": "With this panel be aware of the current time interval being used (top right option with the clock) as it will display what pods have been out during that time entire interval, not just currently out. This can be used to see around when a pod had gone out. ",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pod) (kube_pod_status_ready{condition=\"false\", pod!~\"helm-install.*\"}==1)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods Ready (Namespace)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 4, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_pod_status_ready{condition=\"true\", pod!~\"helm-install.*\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods Not Ready (Namespace)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 4, "x": 4, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_pod_status_ready{condition=\"false\",pod!~\"helm-install.*\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of Containers Ready in Pod ",
     "type": "gauge",
     "description": "With this panel be aware of the current time interval being used (top right option with the clock) as it will display what pods have been out during that time entire interval, not just currently out. This can be used to see around when a pod had gone out. ",
     "gridPos": { "h": 11, "w": 15, "x": 9, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Ready" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(pod) (kube_pod_container_status_running{pod!~\"helm-install.*\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Lifetime Restarts (Pod) {$Namespaces}",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "Restarts" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pod)(kube_pod_container_status_restarts_total{namespace=~\"$Namespaces\", pod!~\"helm-install.*\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod Readiness (Node) {$Namespaces}",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (node) (kube_pod_status_ready{pod!~\"helm-install.*\"}) - (sum by (node) (kube_pod_status_ready{status!=\"ready\", condition=\"false\", namespace=~\"$Namespaces\"}))",
       "legendFormat": "Pods Ready"
      },
      {
       "expr": "sum by (node) (kube_pod_status_ready{status!=\"ready\", condition=\"false\",namespace=~\"$Namespaces\", pod!~\"helm-install.*\"})",
       "legendFormat": "Pods Not Ready"
      },
      {
       "expr": "sum by (node) (kube_pod_status_ready{status!=\"ready\",condition=\"unknown\",namespace=~\"$Namespaces\", pod!~\"helm-install.*\"})",
       "legendFormat": "Condition Unknown"
      }
     ]
    }
   ]
  },
  { "title": "LongHorn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Volumes",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "count(longhorn_volume_capacity_bytes) OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(longhorn_volume_robustness==1) OR on() vector(0)"
    },
    {
     "expr": "count(longhorn_volume_robustness==2) OR on() vector(0)"
    },
    {
     "expr": "count(longhorn_volume_robustness==3) OR on() vector(0)"
    },
    {
     "expr": "count(longhorn_volume_state==2) OR on() vector(0)"
    },
    {
     "expr": "count(longhorn_volume_state==3) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Space Available (Node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((longhorn_node_storage_usage_bytes/longhorn_node_storage_capacity_bytes) * 100)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Space Used (Node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(longhorn_node_storage_usage_bytes/longhorn_node_storage_capacity_bytes) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Space Available (Node)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((longhorn_node_storage_usage_bytes/longhorn_node_storage_capacity_bytes) * 100)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Space Used (Node)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(longhorn_node_storage_usage_bytes/longhorn_node_storage_capacity_bytes) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Space Available (Node)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((longhorn_node_storage_usage_bytes/longhorn_node_storage_capacity_bytes) * 100)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Space Used (Node)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(longhorn_node_storage_usage_bytes/longhorn_node_storage_capacity_bytes) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Space Available (Node)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "longhorn_node_storage_capacity_bytes - longhorn_node_storage_usage_bytes",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Space Used (Node)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "longhorn_node_storage_usage_bytes",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Written (Pod) {$range} {$Namespaces} {$Node}",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(pod, namespace) (rate(container_fs_writes_bytes_total{pod!=\"\",namespace=~\"$Namespaces\",node=~\"$Node\"}[$range]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Bytes Read (Pod) {$range} {$Namespaces} {$Node}",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(pod, namespace) (rate(container_fs_reads_bytes_total{pod!=\"\", namespace=~\"$Namespaces\",node=~\"$Node\"}[$range]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Bytes Written (Pod) {$range} {$Namespaces} {$Node}",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(pod, namespace) (rate(container_fs_writes_bytes_total{pod!=\"\", namespace=~\"$Namespaces\",node=~\"$Node\"}[$range])) / 1000",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Bytes Read (Pod) {$range} {$Namespaces} {$Node}",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(pod, namespace) (rate(container_fs_reads_bytes_total{pod!=\"\",namespace=~\"$Namespaces\",node=~\"$Node\"}[$range])) / 1000",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Bytes Written (Pod) {$range} {$Namespaces} {$Node}",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(pod, namespace) (rate(container_fs_writes_bytes_total{pod!=\"\",namespace=~\"$Namespaces\",node=~\"$Node\"}[$range]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Bytes Read (Pod) {$range} {$Namespaces} {$Node}",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(pod, namespace) (rate(container_fs_reads_bytes_total{pod!=\"\",namespace=~\"$Namespaces\", node=~\"$Node\"}[$range]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage {$range} {$Node} ",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "% of CPU" } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\", node=~\"$Node\"}[$range])) / sum (machine_cpu_cores) * 100",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "CPU Usage (Node) {$range} {$Node}",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "% of CPU" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"$Node\"}[$range])) / sum (machine_cpu_cores) * 100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Average CPU Usage (Node) {$range} {$Node}",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "% of CPU" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\", node=~\"$Node\"}[$range])) / sum (machine_cpu_cores) * 100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage (Pod) {$range} {$Namespaces} {$Node}",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "Cores" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(pod, namespace) (rate(container_cpu_usage_seconds_total{image!=\"\", namespace=~\"$Namespaces\",node=~\"$Node\"}[$range]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage (Pod) {$range} {$Namespaces} {$Node}",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "Cores" } },
     "targets": [
      {
       "expr": "sum by(pod, namespace) (rate(container_cpu_usage_seconds_total{image!=\"\", namespace=~\"$Namespaces\",node=~\"$Node\"}[$range]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage (Namespace) {$range} {$Namespaces} {$Node}",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 5, "x": 19, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "Cores" } },
     "targets": [
      {
       "expr": "sum by(namespace) (rate(container_cpu_usage_seconds_total{image!=\"\", namespace=~\"$Namespaces\",node=~\"$Node\"}[$range]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Memory Usage (Pod) {$Namespaces} {$Node} ",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (pod,namespace) (container_memory_working_set_bytes{namespace=~\"$Namespaces\", container!=\"\", node=~\"$Node\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current Memory Usage (Namespace) {$Namespaces} {$Node}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(namespace) (container_memory_working_set_bytes{container!=\"\", namespace=~\"$Namespaces\",node=~\"$Node\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current Memory Usage (Node) {$Node}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(node) (container_memory_working_set_bytes{container!=\"\", node=~\"$Node\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kubelet HTTP Requests per Second (Method) {$range} {$Node}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (method)(rate(kubelet_http_requests_total{node=~\"$Node\"} [$range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Kubelet HTTP Requests per Second (Node) {$range}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (node)(rate(kubelet_http_requests_total [$range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}